export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';

export const DECK_GET_FAIL = 'DECK_GET_FAIL';
export const DECK_GET_START = 'DECK_GET_START';
export const DECK_GET_SUCCESS = 'DECK_GET_SUCCESS';
export const DECK_POST_FAIL = 'DECK_POST_FAIL';
export const DECK_POST_START = 'DECK_GET_START';
export const DECK_POST_SUCCESS = 'DECK_POST_SUCCESS';
export const DECK_UPDATE_FAIL = 'DECK_UPDATE_FAIL';
export const DECK_UPDATE_START = 'DECK_UPDATE_START';
export const DECK_UPDATE_SUCCESS = 'DECK_UPDATE_SUCCESS';

export const MODAL_CREATE = 'MODAL_CREATE';
export const MODAL_CLEAR = 'MODAL_CLEAR';